
package projet.web.foot.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.7
 * Wed Apr 10 19:58:49 CEST 2024
 * Generated source version: 3.5.7
 */

@XmlRootElement(name = "addPlayer", namespace = "http://www.projet.web.foot")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addPlayer", namespace = "http://www.projet.web.foot")

public class AddPlayer {

    @XmlElement(name = "player")
    private projet.web.foot.Modele.Player player;

    public projet.web.foot.Modele.Player getPlayer() {
        return this.player;
    }

    public void setPlayer(projet.web.foot.Modele.Player newPlayer)  {
        this.player = newPlayer;
    }

}

