
package projet.web.foot.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.7
 * Wed Apr 10 19:58:48 CEST 2024
 * Generated source version: 3.5.7
 */

@XmlRootElement(name = "addTeam", namespace = "http://www.projet.web.foot")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addTeam", namespace = "http://www.projet.web.foot")

public class AddTeam {

    @XmlElement(name = "team")
    private projet.web.foot.Modele.Team team;

    public projet.web.foot.Modele.Team getTeam() {
        return this.team;
    }

    public void setTeam(projet.web.foot.Modele.Team newTeam)  {
        this.team = newTeam;
    }

}

