
package projet.web.foot.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.7
 * Wed Apr 10 19:58:49 CEST 2024
 * Generated source version: 3.5.7
 */

@XmlRootElement(name = "deleteTeam", namespace = "http://www.projet.web.foot")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deleteTeam", namespace = "http://www.projet.web.foot")

public class DeleteTeam {

    @XmlElement(name = "deleteteam")
    private projet.web.foot.Modele.Team deleteteam;

    public projet.web.foot.Modele.Team getDeleteteam() {
        return this.deleteteam;
    }

    public void setDeleteteam(projet.web.foot.Modele.Team newDeleteteam)  {
        this.deleteteam = newDeleteteam;
    }

}

