
package computer.com.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Scanner;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.7
 * 2024-04-10T00:41:48.526+02:00
 * Generated source version: 3.5.7
 *
 */
public final class PlayerWebService_PlayerWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.com.computer", "PlayerWebServiceService");

    private PlayerWebService_PlayerWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PlayerWebServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        PlayerWebServiceService ss = new PlayerWebServiceService(wsdlURL, SERVICE_NAME);
        PlayerWebService port = ss.getPlayerWebServicePort();

        Scanner scanner = new Scanner(System.in);

        System.out.println("Entrez le nom du joueur:");
        String name = scanner.nextLine();

        System.out.println("Entrez le nom de l'equipe:");
        String teamName = scanner.nextLine();

        System.out.println("la poste du joueur:");
        String position = scanner.nextLine();

        Player player = new Player();
        player.setName(name);
        player.setTeamName(teamName);
        player.setPosition(position);

        String result = port.addPlayer(player);
        System.out.println("Result: " + result);

        scanner.close();

        System.exit(0);
    }

}
