package computer.com.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.7
 * 2024-04-10T00:41:48.671+02:00
 * Generated source version: 3.5.7
 *
 */
@WebService(targetNamespace = "http://www.com.computer", name = "PlayerWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface PlayerWebService {

    @WebMethod
    @RequestWrapper(localName = "addPlayer", targetNamespace = "http://www.com.computer", className = "computer.com.client.AddPlayer")
    @ResponseWrapper(localName = "addPlayerResponse", targetNamespace = "http://www.com.computer", className = "computer.com.client.AddPlayerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String addPlayer(

        @WebParam(name = "player", targetNamespace = "")
        computer.com.client.Player player
    );
}
