package foot.web.projet.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.7
 * 2024-04-10T20:01:08.395+02:00
 * Generated source version: 3.5.7
 *
 */
@WebService(targetNamespace = "http://www.projet.web.foot", name = "FootWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface FootWebService {

    @WebMethod
    @RequestWrapper(localName = "addTeam", targetNamespace = "http://www.projet.web.foot", className = "foot.web.projet.client.AddTeam")
    @ResponseWrapper(localName = "addTeamResponse", targetNamespace = "http://www.projet.web.foot", className = "foot.web.projet.client.AddTeamResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String addTeam(

        @WebParam(name = "team", targetNamespace = "")
        foot.web.projet.client.Team team
    );

    @WebMethod
    @RequestWrapper(localName = "deleteTeam", targetNamespace = "http://www.projet.web.foot", className = "foot.web.projet.client.DeleteTeam")
    @ResponseWrapper(localName = "deleteTeamResponse", targetNamespace = "http://www.projet.web.foot", className = "foot.web.projet.client.DeleteTeamResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String deleteTeam(

        @WebParam(name = "deleteteam", targetNamespace = "")
        foot.web.projet.client.Team deleteteam
    );

    @WebMethod
    @RequestWrapper(localName = "addPlayer", targetNamespace = "http://www.projet.web.foot", className = "foot.web.projet.client.AddPlayer")
    @ResponseWrapper(localName = "addPlayerResponse", targetNamespace = "http://www.projet.web.foot", className = "foot.web.projet.client.AddPlayerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String addPlayer(

        @WebParam(name = "player", targetNamespace = "")
        foot.web.projet.client.Player player
    );
}
