
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package foot.web.projet.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.7
 * 2024-04-10T20:01:08.366+02:00
 * Generated source version: 3.5.7
 *
 */

@javax.jws.WebService(
                      serviceName = "FootWeb",
                      portName = "FootService",
                      targetNamespace = "http://www.projet.web.foot",
                      wsdlLocation = "file:/C:/Users/HP/eclipse-workspace/projet.web.foot/src/main/webapp/wsdl/footwebservice.wsdl",
                      endpointInterface = "foot.web.projet.client.FootWebService")

public class FootServiceImpl implements FootWebService {

    private static final Logger LOG = Logger.getLogger(FootServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see foot.web.projet.client.FootWebService#addTeam(foot.web.projet.client.Team team)*
     */
    public java.lang.String addTeam(foot.web.projet.client.Team team) {
        LOG.info("Executing operation addTeam");
        System.out.println(team);
        try {
            java.lang.String _return = "_return909091471";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see foot.web.projet.client.FootWebService#deleteTeam(foot.web.projet.client.Team deleteteam)*
     */
    public java.lang.String deleteTeam(foot.web.projet.client.Team deleteteam) {
        LOG.info("Executing operation deleteTeam");
        System.out.println(deleteteam);
        try {
            java.lang.String _return = "_return-1009354381";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see foot.web.projet.client.FootWebService#addPlayer(foot.web.projet.client.Player player)*
     */
    public java.lang.String addPlayer(foot.web.projet.client.Player player) {
        LOG.info("Executing operation addPlayer");
        System.out.println(player);
        try {
            java.lang.String _return = "_return-1544208358";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
