package foot.web.projet.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.7
 * 2024-04-10T20:01:08.407+02:00
 * Generated source version: 3.5.7
 *
 */
@WebServiceClient(name = "FootWeb",
                  wsdlLocation = "file:/C:/Users/HP/eclipse-workspace/projet.web.foot/src/main/webapp/wsdl/footwebservice.wsdl",
                  targetNamespace = "http://www.projet.web.foot")
public class FootWeb extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.projet.web.foot", "FootWeb");
    public final static QName FootService = new QName("http://www.projet.web.foot", "FootService");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/HP/eclipse-workspace/projet.web.foot/src/main/webapp/wsdl/footwebservice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FootWeb.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/HP/eclipse-workspace/projet.web.foot/src/main/webapp/wsdl/footwebservice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FootWeb(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FootWeb(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FootWeb() {
        super(WSDL_LOCATION, SERVICE);
    }

    public FootWeb(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public FootWeb(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FootWeb(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns FootWebService
     */
    @WebEndpoint(name = "FootService")
    public FootWebService getFootService() {
        return super.getPort(FootService, FootWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FootWebService
     */
    @WebEndpoint(name = "FootService")
    public FootWebService getFootService(WebServiceFeature... features) {
        return super.getPort(FootService, FootWebService.class, features);
    }

}
