
package foot.web.projet.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.7
 * 2024-04-10T20:01:08.234+02:00
 * Generated source version: 3.5.7
 *
 */
public final class FootWebService_FootService_Client {

    private static final QName SERVICE_NAME = new QName("http://www.projet.web.foot", "FootWeb");

    private FootWebService_FootService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = FootWeb.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        FootWeb ss = new FootWeb(wsdlURL, SERVICE_NAME);
        FootWebService port = ss.getFootService();

        {
        System.out.println("Invoking addTeam...");
        foot.web.projet.client.Team _addTeam_team = new foot.web.projet.client.Team();
        _addTeam_team.setCoachName("CoachName-1558114316");
        _addTeam_team.setId(-1296393835);
        _addTeam_team.setLeague("League761802482");
        _addTeam_team.setName("Name1811088419");
        java.lang.String _addTeam__return = port.addTeam(_addTeam_team);
        System.out.println("addTeam.result=" + _addTeam__return);


        }
        {
        System.out.println("Invoking deleteTeam...");
        foot.web.projet.client.Team _deleteTeam_deleteteam = new foot.web.projet.client.Team();
        _deleteTeam_deleteteam.setCoachName("CoachName-1968676309");
        _deleteTeam_deleteteam.setId(-373071092);
        _deleteTeam_deleteteam.setLeague("League245735196");
        _deleteTeam_deleteteam.setName("Name-1103243574");
        java.lang.String _deleteTeam__return = port.deleteTeam(_deleteTeam_deleteteam);
        System.out.println("deleteTeam.result=" + _deleteTeam__return);


        }
        {
        System.out.println("Invoking addPlayer...");
        foot.web.projet.client.Player _addPlayer_player = new foot.web.projet.client.Player();
        _addPlayer_player.setEquipe(1690986114);
        _addPlayer_player.setId(-1424781074);
        _addPlayer_player.setPoste("Poste-1548064578");
        _addPlayer_player.setPrenom("Prenom1268398742");
        _addPlayer_player.setTeamName("TeamName-281039542");
        java.lang.String _addPlayer__return = port.addPlayer(_addPlayer_player);
        System.out.println("addPlayer.result=" + _addPlayer__return);


        }

        System.exit(0);
    }

}
