
package com.computer.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.7
 * Wed Apr 10 00:27:32 CEST 2024
 * Generated source version: 3.5.7
 */

@XmlRootElement(name = "addPlayer", namespace = "http://www.com.computer")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addPlayer", namespace = "http://www.com.computer")

public class AddPlayer {

    @XmlElement(name = "player")
    private com.computer.Player player;

    public com.computer.Player getPlayer() {
        return this.player;
    }

    public void setPlayer(com.computer.Player newPlayer)  {
        this.player = newPlayer;
    }

}

